In [1]:
import numpy as np

1 arange

In [50]:
np. arange(30).reshape(-1,5) # arange : array의 범위를 지정하여, 값의 list를 생성하는 명령어

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [3]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

2 ones, zeros & empty

In [5]:
np.zeros(shape=(10,), dtype=np.int8) # zeros: 0으로 가득찬 ndarray생성 / np.zeros(shape, dtype, order)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.ones((2,5)) # ones : 1로 가득찬 ndarray생성 / np.ones(shape, dtype, order)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.empty(shape=(10,), dtype=np.int8)  # empty : shape만 주어지고 비어있는 ndarray 생성(memory initialization이 되지 않음)

array([ -48, -112,   69,  -73,  126,    1,    0,    0,    0,    0],
      dtype=int8)

In [32]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix) # something_like : 기존 ndarray의 shape 크기만큼 1,0 또는 empty array를 반환

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

3 eye, identity & digonal

In [35]:
np.identity(n=3, dtype=np.int8) # identity : 단위 행렬을 생성 / n-> number of rows

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(N=3, M=5, dtype=np.int8) # eye : 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix) # diag : 대각 행렬의 값을 추출함

array([0, 4, 8])

In [46]:
np.diag(matrix, k=1)

array([1, 5])

In [48]:
np.random.uniform(0,1,10).reshape(2,5) # random sampling : 데이터 분포에 따른 sampling으로 array를 생성

array([[0.45538214, 0.08438894, 0.62940079, 0.26040361, 0.09107181],
       [0.84959779, 0.48371885, 0.71257949, 0.28065642, 0.21655957]])

In [49]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.28111503,  0.46536772, -0.06755204,  1.5023261 , -0.73852897],
       [ 0.41204005,  1.10523213, -2.71438926, -0.96693625, -0.22614558]])