In [1]:
import numpy as np

1. all & any

In [2]:
a = np.arange(10) # all & any : array의 데이터 전부 또는 일부가 조건에 만족 여부 반환
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a>5), np.any(a<0) # 하나라도 만족되면 true

(True, False)

In [5]:
np.all(a>5) , np.all(a < 10) # 모두 다 만족이면 true

(False, True)

2. comparision operation

In [6]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [7]:
test_a == test_b 

array([False, False, False])

In [8]:
(test_a > test_b).any()

True

In [9]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [10]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [11]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [12]:
a

array([1., 3., 0.])

In [13]:
np.where(a > 0, 3, 2)  # a > 0 : 조건 / 3 : True일 경우 반환값 / 2 : False일 경우 반환값

array([3, 3, 2])

In [14]:
np.where(a>0) # index값 반환

(array([0, 1], dtype=int64),)

In [15]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [17]:
a = np.array([1, np.NaN, np.Inf], float) # NaN : not a number
np.isnan(a)

array([False,  True, False])

In [18]:
np.isfinite(a) # isfinite : is finite number

array([ True, False, False])

3. argmax & argmin

In [19]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a) # argmax & argmin : araay 내 최대값 또는 최소값의 index를 반환함

(5, 0)

In [20]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))