1 Numpy 모듈의 호출

In [6]:
import numpy as np

2 array의 생성

In [10]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [8]:
type(test_array[3])

numpy.float64

In [9]:
test_array.dtype # dtype : numpy array의 데이터 type을 반환함

dtype('float64')

In [10]:
test_array

array([1., 4., 5., 8.])

In [11]:
test_array.shape # shape : numpy array의 object의 dimenson 구성을 반환함

(4,)

3 array shape

In [12]:
vector = [1,2,3,4]
np.array(vector, int). shape

(4,)

In [14]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [17]:
tensor = [[[1,2,5,8], [1,2,5,8], [1,2,5,8]], [[1,2,5,8,], [1,2,5,8], [1,2,5,8]], [[1,2,5,8], [1,2,5,8], [1,2,5,8]], [[1,2,5,8], [1,2,5,8], [1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [18]:
np.array(tensor, int).ndim

3

In [19]:
np.array(tensor, int).size

48

4 numpy dtype

In [20]:
a = np.array([[1,2,3], [4.5,5,6]], dtype = int)

In [27]:
np.array([[1,2,3], [4.5,"5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [22]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [25]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.int8).nbytes

6

In [26]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float64).nbytes

48